// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface AllocateDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.AllocateDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanodes = 1;</code>
   */
  java.lang.String getDatanodes();
  /**
   * <code>optional string datanodes = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodesBytes();
}
