// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface AllocateDataNodesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.AllocateDataNodesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 fileSize = 1;</code>
   */
  long getFileSize();
}
