// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface FetchEditsLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.FetchEditsLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string editsLog = 1;</code>
   */
  java.lang.String getEditsLog();
  /**
   * <code>optional string editsLog = 1;</code>
   */
  com.google.protobuf.ByteString
      getEditsLogBytes();
}
