// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

/**
 * Protobuf type {@code com.my.rpc.grpc.namenode.FetchEditsLogResponse}
 */
public  final class FetchEditsLogResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.my.rpc.grpc.namenode.FetchEditsLogResponse)
    FetchEditsLogResponseOrBuilder {
  // Use FetchEditsLogResponse.newBuilder() to construct.
  private FetchEditsLogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchEditsLogResponse() {
    editsLog_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FetchEditsLogResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            editsLog_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.my.rpc.grpc.namenode.NameNodeRpcProto.internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.my.rpc.grpc.namenode.NameNodeRpcProto.internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.my.rpc.grpc.namenode.FetchEditsLogResponse.class, com.my.rpc.grpc.namenode.FetchEditsLogResponse.Builder.class);
  }

  public static final int EDITSLOG_FIELD_NUMBER = 1;
  private volatile java.lang.Object editsLog_;
  /**
   * <code>optional string editsLog = 1;</code>
   */
  public java.lang.String getEditsLog() {
    java.lang.Object ref = editsLog_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      editsLog_ = s;
      return s;
    }
  }
  /**
   * <code>optional string editsLog = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEditsLogBytes() {
    java.lang.Object ref = editsLog_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      editsLog_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEditsLogBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, editsLog_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEditsLogBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, editsLog_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.my.rpc.grpc.namenode.FetchEditsLogResponse)) {
      return super.equals(obj);
    }
    com.my.rpc.grpc.namenode.FetchEditsLogResponse other = (com.my.rpc.grpc.namenode.FetchEditsLogResponse) obj;

    boolean result = true;
    result = result && getEditsLog()
        .equals(other.getEditsLog());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + EDITSLOG_FIELD_NUMBER;
    hash = (53 * hash) + getEditsLog().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.my.rpc.grpc.namenode.FetchEditsLogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.my.rpc.grpc.namenode.FetchEditsLogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.my.rpc.grpc.namenode.FetchEditsLogResponse)
      com.my.rpc.grpc.namenode.FetchEditsLogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.my.rpc.grpc.namenode.NameNodeRpcProto.internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.my.rpc.grpc.namenode.NameNodeRpcProto.internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.my.rpc.grpc.namenode.FetchEditsLogResponse.class, com.my.rpc.grpc.namenode.FetchEditsLogResponse.Builder.class);
    }

    // Construct using com.my.rpc.grpc.namenode.FetchEditsLogResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      editsLog_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.my.rpc.grpc.namenode.NameNodeRpcProto.internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor;
    }

    public com.my.rpc.grpc.namenode.FetchEditsLogResponse getDefaultInstanceForType() {
      return com.my.rpc.grpc.namenode.FetchEditsLogResponse.getDefaultInstance();
    }

    public com.my.rpc.grpc.namenode.FetchEditsLogResponse build() {
      com.my.rpc.grpc.namenode.FetchEditsLogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.my.rpc.grpc.namenode.FetchEditsLogResponse buildPartial() {
      com.my.rpc.grpc.namenode.FetchEditsLogResponse result = new com.my.rpc.grpc.namenode.FetchEditsLogResponse(this);
      result.editsLog_ = editsLog_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.my.rpc.grpc.namenode.FetchEditsLogResponse) {
        return mergeFrom((com.my.rpc.grpc.namenode.FetchEditsLogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.my.rpc.grpc.namenode.FetchEditsLogResponse other) {
      if (other == com.my.rpc.grpc.namenode.FetchEditsLogResponse.getDefaultInstance()) return this;
      if (!other.getEditsLog().isEmpty()) {
        editsLog_ = other.editsLog_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.my.rpc.grpc.namenode.FetchEditsLogResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.my.rpc.grpc.namenode.FetchEditsLogResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object editsLog_ = "";
    /**
     * <code>optional string editsLog = 1;</code>
     */
    public java.lang.String getEditsLog() {
      java.lang.Object ref = editsLog_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        editsLog_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string editsLog = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEditsLogBytes() {
      java.lang.Object ref = editsLog_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        editsLog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string editsLog = 1;</code>
     */
    public Builder setEditsLog(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      editsLog_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string editsLog = 1;</code>
     */
    public Builder clearEditsLog() {
      
      editsLog_ = getDefaultInstance().getEditsLog();
      onChanged();
      return this;
    }
    /**
     * <code>optional string editsLog = 1;</code>
     */
    public Builder setEditsLogBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      editsLog_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.my.rpc.grpc.namenode.FetchEditsLogResponse)
  }

  // @@protoc_insertion_point(class_scope:com.my.rpc.grpc.namenode.FetchEditsLogResponse)
  private static final com.my.rpc.grpc.namenode.FetchEditsLogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.my.rpc.grpc.namenode.FetchEditsLogResponse();
  }

  public static com.my.rpc.grpc.namenode.FetchEditsLogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchEditsLogResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchEditsLogResponse>() {
    public FetchEditsLogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FetchEditsLogResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchEditsLogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchEditsLogResponse> getParserForType() {
    return PARSER;
  }

  public com.my.rpc.grpc.namenode.FetchEditsLogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

