// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanodeInfo = 1;</code>
   */
  java.lang.String getDatanodeInfo();
  /**
   * <code>optional string datanodeInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodeInfoBytes();
}
