// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface GetDataNodeForFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.GetDataNodeForFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
