// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();
}
