// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NamenodeRpc.proto

package com.my.rpc.grpc.namenode;

public final class NamenodeRpcProto {
  private NamenodeRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/my/rpc/grpc/proto/NamenodeRpc.prot" +
      "o\022\030com.my.rpc.grpc.namenode\"/\n\017RegisterR" +
      "equest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020" +
      "RegisterResponse\022\016\n\006status\030\001 \001(\005\"0\n\020Hear" +
      "tbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001" +
      "(\t\"#\n\021HeartbeatResponse\022\016\n\006status\030\001 \001(\0052" +
      "\332\001\n\017NamenodeService\022a\n\010register\022).com.my" +
      ".rpc.grpc.namenode.RegisterRequest\032*.com" +
      ".my.rpc.grpc.namenode.RegisterResponse\022d" +
      "\n\theartbeat\022*.com.my.rpc.grpc.namenode.H",
      "eartbeatRequest\032+.com.my.rpc.grpc.nameno" +
      "de.HeartbeatResponseB.\n\030com.my.rpc.grpc." +
      "namenodeB\020NamenodeRpcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
