// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public final class NameNodeRpcProto {
  private NameNodeRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/my/rpc/grpc/proto/NameNodeRpc.prot" +
      "o\022\030com.my.rpc.grpc.namenode\"/\n\017RegisterR" +
      "equest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020" +
      "RegisterResponse\022\016\n\006status\030\001 \001(\005\"0\n\020Hear" +
      "tbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001" +
      "(\t\"#\n\021HeartbeatResponse\022\016\n\006status\030\001 \001(\005\"" +
      "\034\n\014MkdirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirRe" +
      "sponse\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownReques" +
      "t\022\014\n\004code\030\001 \001(\005\"\"\n\020ShutdownResponse\022\016\n\006s" +
      "tatus\030\001 \001(\005\"*\n\024FetchEditsLogRequest\022\022\n\ns",
      "yncedTxid\030\001 \001(\003\")\n\025FetchEditsLogResponse" +
      "\022\020\n\010editsLog\030\001 \001(\t\"+\n\033UpdateCheckpointTx" +
      "idRequest\022\014\n\004txid\030\001 \001(\003\".\n\034UpdateCheckpo" +
      "intTxidResponse\022\016\n\006status\030\001 \001(\005\"%\n\021Creat" +
      "eFileRequest\022\020\n\010filename\030\001 \001(\t\"$\n\022Create" +
      "FileResponse\022\016\n\006status\030\001 \001(\0052\372\005\n\017NameNod" +
      "eService\022a\n\010register\022).com.my.rpc.grpc.n" +
      "amenode.RegisterRequest\032*.com.my.rpc.grp" +
      "c.namenode.RegisterResponse\022d\n\theartbeat" +
      "\022*.com.my.rpc.grpc.namenode.HeartbeatReq",
      "uest\032+.com.my.rpc.grpc.namenode.Heartbea" +
      "tResponse\022X\n\005mkdir\022&.com.my.rpc.grpc.nam" +
      "enode.MkdirRequest\032\'.com.my.rpc.grpc.nam" +
      "enode.MkdirResponse\022a\n\010shutdown\022).com.my" +
      ".rpc.grpc.namenode.ShutdownRequest\032*.com" +
      ".my.rpc.grpc.namenode.ShutdownResponse\022p" +
      "\n\rfetchEditsLog\022..com.my.rpc.grpc.nameno" +
      "de.FetchEditsLogRequest\032/.com.my.rpc.grp" +
      "c.namenode.FetchEditsLogResponse\022\205\001\n\024upd" +
      "ateCheckpointTxid\0225.com.my.rpc.grpc.name",
      "node.UpdateCheckpointTxidRequest\0326.com.m" +
      "y.rpc.grpc.namenode.UpdateCheckpointTxid" +
      "Response\022g\n\ncreateFile\022+.com.my.rpc.grpc" +
      ".namenode.CreateFileRequest\032,.com.my.rpc" +
      ".grpc.namenode.CreateFileResponseB.\n\030com" +
      ".my.rpc.grpc.namenodeB\020NameNodeRpcProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor,
        new java.lang.String[] { "SyncedTxid", });
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor,
        new java.lang.String[] { "EditsLog", });
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
