// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public final class NameNodeRpcProto {
  private NameNodeRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/my/rpc/grpc/proto/NameNodeRpc.prot" +
      "o\022\030com.my.rpc.grpc.namenode\"@\n\017RegisterR" +
      "equest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\017\n\007" +
      "nioPort\030\003 \001(\005\"\"\n\020RegisterResponse\022\016\n\006sta" +
      "tus\030\001 \001(\005\"A\n\020HeartbeatRequest\022\n\n\002ip\030\001 \001(" +
      "\t\022\020\n\010hostname\030\002 \001(\t\022\017\n\007nioPort\030\003 \001(\005\"5\n\021" +
      "HeartbeatResponse\022\016\n\006status\030\001 \001(\005\022\020\n\010com" +
      "mands\030\002 \001(\t\"\034\n\014MkdirRequest\022\014\n\004path\030\001 \001(" +
      "\t\"\037\n\rMkdirResponse\022\016\n\006status\030\001 \001(\005\"\037\n\017Sh" +
      "utdownRequest\022\014\n\004code\030\001 \001(\005\"\"\n\020ShutdownR",
      "esponse\022\016\n\006status\030\001 \001(\005\"*\n\024FetchEditsLog" +
      "Request\022\022\n\nsyncedTxid\030\001 \001(\003\")\n\025FetchEdit" +
      "sLogResponse\022\020\n\010editsLog\030\001 \001(\t\"+\n\033Update" +
      "CheckpointTxidRequest\022\014\n\004txid\030\001 \001(\003\".\n\034U" +
      "pdateCheckpointTxidResponse\022\016\n\006status\030\001 " +
      "\001(\005\"%\n\021CreateFileRequest\022\020\n\010filename\030\001 \001" +
      "(\t\"$\n\022CreateFileResponse\022\016\n\006status\030\001 \001(\005" +
      "\",\n\030AllocateDataNodesRequest\022\020\n\010fileSize" +
      "\030\001 \001(\003\".\n\031AllocateDataNodesResponse\022\021\n\td" +
      "atanodes\030\001 \001(\t\"N\n\034InformReplicaReceivedR",
      "equest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\022\020\n\010" +
      "filename\030\003 \001(\t\"/\n\035InformReplicaReceivedR" +
      "esponse\022\016\n\006status\030\001 \001(\005\"k\n ReportComplet" +
      "eStorageInfoRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostn" +
      "ame\030\002 \001(\t\022\021\n\tfilenames\030\003 \001(\t\022\026\n\016storedDa" +
      "taSize\030\004 \001(\003\"3\n!ReportCompleteStorageInf" +
      "oResponse\022\016\n\006status\030\001 \001(\005\"I\n\031GetDataNode" +
      "ForFileRequest\022\020\n\010filename\030\001 \001(\t\022\032\n\022excl" +
      "udedDataNodeId\030\002 \001(\t\"2\n\032GetDataNodeForFi" +
      "leResponse\022\024\n\014datanodeInfo\030\001 \001(\t\"I\n\031Real",
      "locateDataNodeRequest\022\020\n\010fileSize\030\001 \001(\003\022" +
      "\032\n\022excludedDataNodeId\030\002 \001(\t\".\n\032Reallocat" +
      "eDataNodeResponse\022\020\n\010datanode\030\001 \001(\t2\234\013\n\017" +
      "NameNodeService\022a\n\010register\022).com.my.rpc" +
      ".grpc.namenode.RegisterRequest\032*.com.my." +
      "rpc.grpc.namenode.RegisterResponse\022d\n\the" +
      "artbeat\022*.com.my.rpc.grpc.namenode.Heart" +
      "beatRequest\032+.com.my.rpc.grpc.namenode.H" +
      "eartbeatResponse\022X\n\005mkdir\022&.com.my.rpc.g" +
      "rpc.namenode.MkdirRequest\032\'.com.my.rpc.g",
      "rpc.namenode.MkdirResponse\022a\n\010shutdown\022)" +
      ".com.my.rpc.grpc.namenode.ShutdownReques" +
      "t\032*.com.my.rpc.grpc.namenode.ShutdownRes" +
      "ponse\022p\n\rfetchEditsLog\022..com.my.rpc.grpc" +
      ".namenode.FetchEditsLogRequest\032/.com.my." +
      "rpc.grpc.namenode.FetchEditsLogResponse\022" +
      "\205\001\n\024updateCheckpointTxid\0225.com.my.rpc.gr" +
      "pc.namenode.UpdateCheckpointTxidRequest\032" +
      "6.com.my.rpc.grpc.namenode.UpdateCheckpo" +
      "intTxidResponse\022g\n\ncreateFile\022+.com.my.r",
      "pc.grpc.namenode.CreateFileRequest\032,.com" +
      ".my.rpc.grpc.namenode.CreateFileResponse" +
      "\022|\n\021allocateDataNodes\0222.com.my.rpc.grpc." +
      "namenode.AllocateDataNodesRequest\0323.com." +
      "my.rpc.grpc.namenode.AllocateDataNodesRe" +
      "sponse\022\210\001\n\025informReplicaReceived\0226.com.m" +
      "y.rpc.grpc.namenode.InformReplicaReceive" +
      "dRequest\0327.com.my.rpc.grpc.namenode.Info" +
      "rmReplicaReceivedResponse\022\224\001\n\031reportComp" +
      "leteStorageInfo\022:.com.my.rpc.grpc.nameno",
      "de.ReportCompleteStorageInfoRequest\032;.co" +
      "m.my.rpc.grpc.namenode.ReportCompleteSto" +
      "rageInfoResponse\022\177\n\022getDataNodeForFile\0223" +
      ".com.my.rpc.grpc.namenode.GetDataNodeFor" +
      "FileRequest\0324.com.my.rpc.grpc.namenode.G" +
      "etDataNodeForFileResponse\022\177\n\022reallocateD" +
      "ataNode\0223.com.my.rpc.grpc.namenode.Reall" +
      "ocateDataNodeRequest\0324.com.my.rpc.grpc.n" +
      "amenode.ReallocateDataNodeResponseB.\n\030co" +
      "m.my.rpc.grpc.namenodeB\020NameNodeRpcProto",
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "NioPort", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", "Commands", });
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_FetchEditsLogRequest_descriptor,
        new java.lang.String[] { "SyncedTxid", });
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_FetchEditsLogResponse_descriptor,
        new java.lang.String[] { "EditsLog", });
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidRequest_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_UpdateCheckpointTxidResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_CreateFileRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_CreateFileResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesRequest_descriptor,
        new java.lang.String[] { "FileSize", });
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_AllocateDataNodesResponse_descriptor,
        new java.lang.String[] { "Datanodes", });
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "Filename", });
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_InformReplicaReceivedResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", "Filenames", "StoredDataSize", });
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ReportCompleteStorageInfoResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileRequest_descriptor,
        new java.lang.String[] { "Filename", "ExcludedDataNodeId", });
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_GetDataNodeForFileResponse_descriptor,
        new java.lang.String[] { "DatanodeInfo", });
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeRequest_descriptor,
        new java.lang.String[] { "FileSize", "ExcludedDataNodeId", });
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ReallocateDataNodeResponse_descriptor,
        new java.lang.String[] { "Datanode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
