// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public final class NameNodeRpcProto {
  private NameNodeRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/my/rpc/grpc/proto/NameNodeRpc.prot" +
      "o\022\030com.my.rpc.grpc.namenode\"/\n\017RegisterR" +
      "equest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001(\t\"\"\n\020" +
      "RegisterResponse\022\016\n\006status\030\001 \001(\005\"0\n\020Hear" +
      "tbeatRequest\022\n\n\002ip\030\001 \001(\t\022\020\n\010hostname\030\002 \001" +
      "(\t\"#\n\021HeartbeatResponse\022\016\n\006status\030\001 \001(\005\"" +
      "\034\n\014MkdirRequest\022\014\n\004path\030\001 \001(\t\"\037\n\rMkdirRe" +
      "sponse\022\016\n\006status\030\001 \001(\005\"\037\n\017ShutdownReques" +
      "t\022\014\n\004code\030\001 \001(\t\"\"\n\020ShutdownResponse\022\016\n\006s" +
      "tatus\030\001 \001(\0052\227\003\n\017NameNodeService\022a\n\010regis",
      "ter\022).com.my.rpc.grpc.namenode.RegisterR" +
      "equest\032*.com.my.rpc.grpc.namenode.Regist" +
      "erResponse\022d\n\theartbeat\022*.com.my.rpc.grp" +
      "c.namenode.HeartbeatRequest\032+.com.my.rpc" +
      ".grpc.namenode.HeartbeatResponse\022X\n\005mkdi" +
      "r\022&.com.my.rpc.grpc.namenode.MkdirReques" +
      "t\032\'.com.my.rpc.grpc.namenode.MkdirRespon" +
      "se\022a\n\010shutdown\022).com.my.rpc.grpc.namenod" +
      "e.ShutdownRequest\032*.com.my.rpc.grpc.name" +
      "node.ShutdownResponseB.\n\030com.my.rpc.grpc",
      ".namenodeB\020NameNodeRpcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_my_rpc_grpc_namenode_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_my_rpc_grpc_namenode_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_RegisterResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatRequest_descriptor,
        new java.lang.String[] { "Ip", "Hostname", });
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_my_rpc_grpc_namenode_MkdirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_my_rpc_grpc_namenode_MkdirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_MkdirResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownRequest_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_my_rpc_grpc_namenode_ShutdownResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
