// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface ReallocateDataNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.ReallocateDataNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string datanode = 1;</code>
   */
  java.lang.String getDatanode();
  /**
   * <code>optional string datanode = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatanodeBytes();
}
