// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface ShutdownRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.ShutdownRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
