// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/my/rpc/grpc/proto/NameNodeRpc.proto

package com.my.rpc.grpc.namenode;

public interface UpdateCheckpointTxidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.my.rpc.grpc.namenode.UpdateCheckpointTxidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 txid = 1;</code>
   */
  long getTxid();
}
